services:
  - type: web
    name: barninz-shop
    env: node
    buildCommand: npm install && npx vite build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
